- name: config zabbix agent
  lineinfile:
    dest: /etc/zabbix/zabbix_agentd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'Server=127.0.0.1', line: 'Server={{ip_server}}' }
    - { regexp: 'ServerActive=127.0.0.1', line: 'ServerActive={{ip_server}}' }
