#- name: install repo zabbix
#  command: rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
- name: install zabbix-agent
  yum:
   name: zabbix-agent
   state: latest
  notify: start enable zabbix-agent

