- name: config time zabbix
  lineinfile:
    dest: /etc/httpd/conf.d/zabbix.conf
    regexp: '# php_value date.timezone Europe/Riga'
    line: 'php_value date.timezone Asian/Ho_Chi_Minh'

- name: config zabbix server
  lineinfile:
    dest: /etc/zabbix/zabbix_server.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '# DBHost=localhost', line: 'DBHost=localhost' }
    - { regexp: '# DBPassword=', line: 'DBPassword={{pass_user_mysql}}' }
