- name: install repo epel
  yum:
   name: epel-release

- name: install repo zabbix
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm

- name: Add repository mariadb
  template:
   src: repo_mariadb.j2
   dest: /etc/yum.repos.d/MariaDB.repo
  
- name: install package
  yum:
   name: "{{item}}"
   state: latest
  with_items:
   - httpd
   - httpd-devel 
   - MariaDB 
   - MariaDB-server
   - php-mysql 
   - php-pear 
   - php-common 
   - php-gd 
   - php-devel 
   - php 
   - php-mbstring 
   - php-cli 
   - php-mysql 
   - php-xml
   - zabbix-server-mysql
   - zabbix-web-mysql
   - MySQL-python
  notify: start enable services centos
- name: start service
  service:
   name: mysql
   state: started
