- name: install package prerequisite
  apt: 
   name: "{{item}}"
   state: latest
  with_items:
   - apache2 
   - mysql-server 
   - php5
   - php5-cli 
   - php5-common 
   - php5-mysql

- name: Add repository zabbix 
  command: "{{item}}"
  with_items:
   - wget http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb
   - dpkg -i zabbix-release_3.0-1+trusty_all.deb
   - apt-get update

- name: install package
  apt:
   name: "{{item}}"
   state: latest
  with_items:
   - zabbix-server-mysql 
   - zabbix-frontend-php
  notify: start enable services ubuntu
- name: start service
  service:
   name: mysql
   state: started
