- name: remove config default
  command: "{{item}}"
  with_items:
   - rm /usr/share/cacti/include/config.php
   - rm /etc/httpd/conf.d/cacti.conf

- name: configure database cacti
  template: 
   src: config.php.j2
   dest: /usr/share/cacti/include/config.php


- name: config cacti
  template:
   src: cacti.conf.j2
   dest: /etc/httpd/conf.d/cacti.conf
  notify: restart webserver

